### ISSUE TITLE
missing containers in src? 

### ISSUE THREAD

**Issue by thomashoddinott** [bmvantunes/youtube-2020-feb-nextjs-part1#3]
From around 16:45 in the video we create a container to only expose components that should be exposed to routing. Are we missing this part from the end of the video? I see in part2 we have everything that we did from this part. Was just wondering if it should not be in this repo too. Thanks for the videos.

**Comment by bmvantunes** [comment]
Thank you Thomas 😊

Well... At the time I spent quite a while thinking if I should add that bit of code to the first video repo or keep it as simple as possible to not confuse people reading the code. 

Ultimately I decided to not include it in the first one because it was a beginners video. It's included in the second video repo 😊
